DROP TABLE IF EXISTS sensors CASCADE;

CREATE TABLE IF NOT EXISTS sensors
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL
);

SELECT *
FROM sensors;

DROP TABLE IF EXISTS sensor_data CASCADE;

CREATE TABLE IF NOT EXISTS sensor_data
(
    id           INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_weather TIMESTAMP NOT NULL,
    value        FLOAT     NOT NULL,
    raining      BOOLEAN   NOT NULL,
    sensor_id    INT REFERENCES sensors (id) ON DELETE CASCADE,
    creat_at     TIMESTAMP NOT NULL
);

INSERT INTO sensor_data(date_weather, value, raining, sensor_id, creat_at)
VALUES ('2023-09-23 22:00', 20.3, true, 1, now());

SELECT *
FROM sensor_data;